CREATE TABLE ADCAMPAIGN
(
    PARTNERID VARCHAR(20) NOT NULL PRIMARY KEY,
	DURATION NUMBER(19) NOT NULL,
	ADCONTENT VARCHAR2(50) NOT NULL,
);


INSERT INTO ADCAMPAIGN (PARTNERID, DURATION, ADCONTENT) VALUES ('1', 1234, 'TEST');
INSERT INTO ADCAMPAIGN (PARTNERID, DURATION, ADCONTENT) VALUES ('2', 1234, 'TEST');
INSERT INTO ADCAMPAIGN (PARTNERID, DURATION, ADCONTENT) VALUES ('3', 1234, 'TEST');
commit ;